apiVersion: v1
kind: Service
metadata:
  name: daa-kafka-hs
  namespace: daa-stack
spec:
  clusterIP: None
  selector:
    app: daa-kafka
  ports:
    - port: 9092
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: daa-kafka
  namespace: daa-stack
spec:
  serviceName: "daa-kafka-hs"
  replicas: 2
  selector:
    matchLabels:
      app: daa-kafka
  template:
    metadata:
      labels:
        app: daa-kafka
    spec:
      securityContext:
        fsGroup: 1000
      containers:
      - name: kafka
        image: wurstmeister/kafka:2.13-2.8.1
        ports:
        - containerPort: 9092
        env:
        - name: KAFKA_ZOOKEEPER_CONNECT
          value: "daa-zoo-0.daa-zoo-hs:2181,daa-zoo-1.daa-zoo-hs:2181,daa-zoo-2.daa-zoo-hs:2181"
        - name: KAFKA_LISTENERS
          value: "INSIDE://0.0.0.0:19092,OUTSIDE://0.0.0.0:9092"
        - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
          value: "INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT"
        - name: KAFKA_INTER_BROKER_LISTENER_NAME
          value: "INSIDE"
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        # 핵심 수정 사항: 실행 시점에 변수를 치환하여 전달
        command:
        - sh
        - -c
        - |
          export KAFKA_ADVERTISED_LISTENERS="INSIDE://${POD_NAME}.daa-kafka-hs.daa-stack.svc.cluster.local:19092,OUTSIDE://${POD_IP}:9092"
          exec start-kafka.sh
        volumeMounts:
        - name: kafka-logs
          mountPath: /kafka/logs
  volumeClaimTemplates:
  - metadata:
      name: kafka-logs
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "nfs-sc"
      resources:
        requests:
          storage: 2Gi